micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-massage-size: 1024


datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/minha_base`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

#jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true


itau:
  erp:
    url: ${$ERP_API:`http://localhost:9091/api/v1/clientes`}


bancocentral:
  pix:
    url: ${$BCB_API:`http://localhost:8082`}